### ISSUE TITLE
Make external links open in a new window

### ISSUE THREAD

**Issue by AndrewNatoli** [OpenCLTBrigade/vote-clt-site#1]
Should also include `rel="noopener noreferrer"`

https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/

**Comment by jarrettkong** [comment]
Are there specific pages that you want this for or all anchor tags in the codebase?

**Comment by AndrewNatoli** [comment]
Hey @jarrettkong - It would be great to have external links open in a new window on the three internal pages (markdown files in the root directory) as well as in the footer (footer.html)

**Comment by jarrettkong** [comment]
Done!

**Comment by AndrewNatoli** [comment]
Thanks! 😄

_Resolved by #2 _
